import { MetadataRoute } from 'next'
 
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/qr-code-generator',
          '/qr-code-analytics',
          '/pricing',
          '/features',
          '/blog',
          '/faq',
          '/about',
          '/contact',
          '/privacy',
          '/terms',
          '/qr-code-for-*',
          '/wifi-qr-code-generator',
          '/contact-qr-code-generator',
          '/qr-code-api',
          '/qr-code-size-calculator',
          '/qr-code-readability-checker',
          '/qr-code-roi-calculator',
          '/qr-code-compliance-checker',
          '/restaurant-qr-code-solutions',
          '/real-estate-qr-code-marketing',
          '/retail-qr-code-strategies',
          '/healthcare-qr-code-solutions',
          '/education-qr-code-tools',
        ],
        disallow: [
          '/dashboard/',
          '/api/',
          '/auth/',
          '/debug/',
          '/_next/',
          '/share/',
          '/r/', // QR code redirects
          '/display/', // QR code display pages
          '/analytics/', // User analytics (private)
          '/google-oauth/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/qr-code-generator',
          '/qr-code-analytics',
          '/pricing',
          '/features',
          '/blog',
          '/faq',
          '/about',
          '/contact',
          '/privacy',
          '/terms',
          '/qr-code-for-*',
          '/wifi-qr-code-generator',
          '/contact-qr-code-generator',
          '/qr-code-api',
          '/qr-code-size-calculator',
          '/qr-code-readability-checker',
          '/qr-code-roi-calculator',
          '/qr-code-compliance-checker',
          '/restaurant-qr-code-solutions',
          '/real-estate-qr-code-marketing',
          '/retail-qr-code-strategies',
          '/healthcare-qr-code-solutions',
          '/education-qr-code-tools',
        ],
        disallow: [
          '/dashboard/',
          '/api/',
          '/auth/',
          '/debug/',
          '/_next/',
          '/share/',
          '/r/',
          '/display/',
          '/analytics/',
          '/google-oauth/',
        ],
        crawlDelay: 0,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/qr-code-generator',
          '/qr-code-analytics',
          '/pricing',
          '/features',
          '/blog',
          '/faq',
          '/about',
          '/contact',
          '/privacy',
          '/terms',
          '/qr-code-for-*',
          '/wifi-qr-code-generator',
          '/contact-qr-code-generator',
          '/qr-code-api',
          '/qr-code-size-calculator',
          '/qr-code-readability-checker',
          '/qr-code-roi-calculator',
          '/qr-code-compliance-checker',
          '/restaurant-qr-code-solutions',
          '/real-estate-qr-code-marketing',
          '/retail-qr-code-strategies',
          '/healthcare-qr-code-solutions',
          '/education-qr-code-tools',
        ],
        disallow: [
          '/dashboard/',
          '/api/',
          '/auth/',
          '/debug/',
          '/_next/',
          '/share/',
          '/r/',
          '/display/',
          '/analytics/',
          '/google-oauth/',
        ],
        crawlDelay: 1,
      }
    ],
    sitemap: 'https://theqrcode.io/sitemap.xml',
    host: 'https://theqrcode.io',
  }
}
